In [2]:
import numpy as np
a = np.array([1, 2, 3, 4, 5], dtype=float)
print(a + 2)  # [3. 4. 5. 6. 7.]
print(a - 1)  # [0. 1. 2. 3. 4.]

[3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4.]


In [4]:
a = np.array([1, 2, 3, 4, 5], dtype=float)

print(a)  # [1. 2. 3. 4. 5.]

b = 5*a

print(b)  # [ 5. 10. 15. 20. 25.]

[1. 2. 3. 4. 5.]
[ 5. 10. 15. 20. 25.]


In [5]:
import numpy as np

a = np.array([1, 2, 3, 4, 5], dtype=float)
print(a.size)  # 5


5


In [6]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)  # [5 7 9]
print(a - b)  # [-3 -3 -3]


[5 7 9]
[-3 -3 -3]


In [7]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a * b)  # [ 4 10 18]


[ 4 10 18]
